def eul29(n):
    """How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ n =100 and 2 ≤ b ≤ n = 100?"""
    return len(set([(a ** b) for a in range(2, n + 1) for b in range(2, n + 1)]))

print(eul29(100))
# 9183
